repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
  -   repo: local
      hooks:
      -   id: brownie-test
          name: brownie-test
          entry: brownie-test
          language: system